services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:1_27_alpine_custom
    container_name: container_nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      network_php:
        ipv4_address: 172.16.0.10

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: php:8_4_fpm_alpine_custom
    container_name: container_php
    restart: always
    working_dir: /var/www
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9000/fpm-ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      network_php:
        ipv4_address: 172.16.0.11

  database:
    image: postgres:17.5
    container_name: container_postgresql
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./postgresql_initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      network_php:
        ipv4_address: 172.16.0.12

  adminer:
    image: adminer:5-standalone
    container_name: container_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      network_php:
        ipv4_address: 172.16.0.13

networks:
  network_php:
    name: global_php
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
